### ISSUE TITLE
Improve UI for Create Deal and Deal Details

### ISSUE THREAD

**Issue by nmhung** [LateFire/Deals#15]
- Apply transition for these screen.
- Fix bug for UI.
- Add function Save Deal for Customer User.

**Comment by weibeld** [comment]
"Add function Save Deal for Customer User" done by @weibeld in commit b89962439309b145da59c406d6dd329d9a7dc429.

**Comment by nmhung** [comment]
Done all in commit 545d5a5af092c1054b816b7d2eceb43fa8c6998a
